// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: game/game.proto

package game

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Запрос и ответ для начала новой игры
type NewGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewGameRequest) Reset() {
	*x = NewGameRequest{}
	mi := &file_game_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewGameRequest) ProtoMessage() {}

func (x *NewGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewGameRequest.ProtoReflect.Descriptor instead.
func (*NewGameRequest) Descriptor() ([]byte, []int) {
	return file_game_game_proto_rawDescGZIP(), []int{0}
}

type NewGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	PlayerCards   []string               `protobuf:"bytes,2,rep,name=player_cards,json=playerCards,proto3" json:"player_cards,omitempty"`
	DealerCard    string                 `protobuf:"bytes,3,opt,name=dealer_card,json=dealerCard,proto3" json:"dealer_card,omitempty"`
	PlayerTotal   int32                  `protobuf:"varint,4,opt,name=player_total,json=playerTotal,proto3" json:"player_total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewGameResponse) Reset() {
	*x = NewGameResponse{}
	mi := &file_game_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewGameResponse) ProtoMessage() {}

func (x *NewGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewGameResponse.ProtoReflect.Descriptor instead.
func (*NewGameResponse) Descriptor() ([]byte, []int) {
	return file_game_game_proto_rawDescGZIP(), []int{1}
}

func (x *NewGameResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *NewGameResponse) GetPlayerCards() []string {
	if x != nil {
		return x.PlayerCards
	}
	return nil
}

func (x *NewGameResponse) GetDealerCard() string {
	if x != nil {
		return x.DealerCard
	}
	return ""
}

func (x *NewGameResponse) GetPlayerTotal() int32 {
	if x != nil {
		return x.PlayerTotal
	}
	return 0
}

// Запрос и ответ для операции Hit
type HitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HitRequest) Reset() {
	*x = HitRequest{}
	mi := &file_game_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HitRequest) ProtoMessage() {}

func (x *HitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HitRequest.ProtoReflect.Descriptor instead.
func (*HitRequest) Descriptor() ([]byte, []int) {
	return file_game_game_proto_rawDescGZIP(), []int{2}
}

func (x *HitRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type HitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerCards   []string               `protobuf:"bytes,1,rep,name=player_cards,json=playerCards,proto3" json:"player_cards,omitempty"`
	PlayerTotal   int32                  `protobuf:"varint,2,opt,name=player_total,json=playerTotal,proto3" json:"player_total,omitempty"`
	Finished      bool                   `protobuf:"varint,3,opt,name=finished,proto3" json:"finished,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HitResponse) Reset() {
	*x = HitResponse{}
	mi := &file_game_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HitResponse) ProtoMessage() {}

func (x *HitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HitResponse.ProtoReflect.Descriptor instead.
func (*HitResponse) Descriptor() ([]byte, []int) {
	return file_game_game_proto_rawDescGZIP(), []int{3}
}

func (x *HitResponse) GetPlayerCards() []string {
	if x != nil {
		return x.PlayerCards
	}
	return nil
}

func (x *HitResponse) GetPlayerTotal() int32 {
	if x != nil {
		return x.PlayerTotal
	}
	return 0
}

func (x *HitResponse) GetFinished() bool {
	if x != nil {
		return x.Finished
	}
	return false
}

// Запрос и ответ для операции Stand
type StandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StandRequest) Reset() {
	*x = StandRequest{}
	mi := &file_game_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StandRequest) ProtoMessage() {}

func (x *StandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StandRequest.ProtoReflect.Descriptor instead.
func (*StandRequest) Descriptor() ([]byte, []int) {
	return file_game_game_proto_rawDescGZIP(), []int{4}
}

func (x *StandRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type StandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DealerCards   []string               `protobuf:"bytes,1,rep,name=dealer_cards,json=dealerCards,proto3" json:"dealer_cards,omitempty"`
	DealerTotal   int32                  `protobuf:"varint,2,opt,name=dealer_total,json=dealerTotal,proto3" json:"dealer_total,omitempty"`
	Outcome       string                 `protobuf:"bytes,3,opt,name=outcome,proto3" json:"outcome,omitempty"` // "win", "lose", "push"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StandResponse) Reset() {
	*x = StandResponse{}
	mi := &file_game_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StandResponse) ProtoMessage() {}

func (x *StandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StandResponse.ProtoReflect.Descriptor instead.
func (*StandResponse) Descriptor() ([]byte, []int) {
	return file_game_game_proto_rawDescGZIP(), []int{5}
}

func (x *StandResponse) GetDealerCards() []string {
	if x != nil {
		return x.DealerCards
	}
	return nil
}

func (x *StandResponse) GetDealerTotal() int32 {
	if x != nil {
		return x.DealerTotal
	}
	return 0
}

func (x *StandResponse) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

var File_game_game_proto protoreflect.FileDescriptor

const file_game_game_proto_rawDesc = "" +
	"\n" +
	"\x0fgame/game.proto\x12\x04game\"\x10\n" +
	"\x0eNewGameRequest\"\x97\x01\n" +
	"\x0fNewGameResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12!\n" +
	"\fplayer_cards\x18\x02 \x03(\tR\vplayerCards\x12\x1f\n" +
	"\vdealer_card\x18\x03 \x01(\tR\n" +
	"dealerCard\x12!\n" +
	"\fplayer_total\x18\x04 \x01(\x05R\vplayerTotal\"+\n" +
	"\n" +
	"HitRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"o\n" +
	"\vHitResponse\x12!\n" +
	"\fplayer_cards\x18\x01 \x03(\tR\vplayerCards\x12!\n" +
	"\fplayer_total\x18\x02 \x01(\x05R\vplayerTotal\x12\x1a\n" +
	"\bfinished\x18\x03 \x01(\bR\bfinished\"-\n" +
	"\fStandRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"o\n" +
	"\rStandResponse\x12!\n" +
	"\fdealer_cards\x18\x01 \x03(\tR\vdealerCards\x12!\n" +
	"\fdealer_total\x18\x02 \x01(\x05R\vdealerTotal\x12\x18\n" +
	"\aoutcome\x18\x03 \x01(\tR\aoutcome2\xa3\x01\n" +
	"\vGameService\x126\n" +
	"\aNewGame\x12\x14.game.NewGameRequest\x1a\x15.game.NewGameResponse\x12*\n" +
	"\x03Hit\x12\x10.game.HitRequest\x1a\x11.game.HitResponse\x120\n" +
	"\x05Stand\x12\x12.game.StandRequest\x1a\x13.game.StandResponseB6Z4github.com/Arsencchikkk/projectt/Handbook/proto/gameb\x06proto3"

var (
	file_game_game_proto_rawDescOnce sync.Once
	file_game_game_proto_rawDescData []byte
)

func file_game_game_proto_rawDescGZIP() []byte {
	file_game_game_proto_rawDescOnce.Do(func() {
		file_game_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_game_proto_rawDesc), len(file_game_game_proto_rawDesc)))
	})
	return file_game_game_proto_rawDescData
}

var file_game_game_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_game_game_proto_goTypes = []any{
	(*NewGameRequest)(nil),  // 0: game.NewGameRequest
	(*NewGameResponse)(nil), // 1: game.NewGameResponse
	(*HitRequest)(nil),      // 2: game.HitRequest
	(*HitResponse)(nil),     // 3: game.HitResponse
	(*StandRequest)(nil),    // 4: game.StandRequest
	(*StandResponse)(nil),   // 5: game.StandResponse
}
var file_game_game_proto_depIdxs = []int32{
	0, // 0: game.GameService.NewGame:input_type -> game.NewGameRequest
	2, // 1: game.GameService.Hit:input_type -> game.HitRequest
	4, // 2: game.GameService.Stand:input_type -> game.StandRequest
	1, // 3: game.GameService.NewGame:output_type -> game.NewGameResponse
	3, // 4: game.GameService.Hit:output_type -> game.HitResponse
	5, // 5: game.GameService.Stand:output_type -> game.StandResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_game_game_proto_init() }
func file_game_game_proto_init() {
	if File_game_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_game_proto_rawDesc), len(file_game_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_game_game_proto_goTypes,
		DependencyIndexes: file_game_game_proto_depIdxs,
		MessageInfos:      file_game_game_proto_msgTypes,
	}.Build()
	File_game_game_proto = out.File
	file_game_game_proto_goTypes = nil
	file_game_game_proto_depIdxs = nil
}
